### ISSUE TITLE
首次打开页面会重复统计，百度和谷歌都存在这种情况。

### ISSUE THREAD

**Issue by liuwave** [sylingd/vuepress-baidu-google-analytics#1]
![image](https://user-images.githubusercontent.com/6533126/79638511-47652d00-81b8-11ea-9117-25df3c268e16.png)

![image](https://user-images.githubusercontent.com/6533126/79638527-6794ec00-81b8-11ea-89cd-2fae8472c3f7.png)

**Comment by sylingd** [comment]
已修复

**Comment by liuwave** [comment]
(๑•̀ㅂ•́)و✧，辛苦啦
